"""Add PendingEmployeeInfo

Revision ID: 000a6c7d74b5
Revises: 0f49b74b6459
Create Date: 2025-06-14 08:59:02.892977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000a6c7d74b5'
down_revision = '0f49b74b6459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Gioitinh', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('Macv', sa.String(length=50), nullable=True))
        batch_op.alter_column('TenNV',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('MAHD',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('MaPB',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('MaCV')
        batch_op.drop_column('GioiTinh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GioiTinh', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('MaCV', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('MaPB',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('MAHD',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('TenNV',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('Macv')
        batch_op.drop_column('Gioitinh')

    # ### end Alembic commands ###
