"""Tạo bảng employee_info liên kết với employee_code

Revision ID: 0f49b74b6459
Revises: 8e26736955f3
Create Date: 2025-06-14 07:48:30.026396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f49b74b6459'
down_revision = '8e26736955f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_info',
    sa.Column('MaNV', sa.String(length=10), nullable=False),
    sa.Column('TenNV', sa.String(length=100), nullable=False),
    sa.Column('SDT', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.String(length=10), nullable=True),
    sa.Column('NoiSinh', sa.String(length=100), nullable=True),
    sa.Column('QuocTich', sa.String(length=50), nullable=True),
    sa.Column('MAHD', sa.String(length=20), nullable=True),
    sa.Column('MaPB', sa.String(length=20), nullable=True),
    sa.Column('MaCV', sa.String(length=20), nullable=True),
    sa.Column('Luong', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['MaNV'], ['user.employee_code'], ),
    sa.PrimaryKeyConstraint('MaNV')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_info')
    # ### end Alembic commands ###
