"""Add ot_hours to Attendance

Revision ID: 2f4d5ca361d0
Revises: a41e2421f248
Create Date: 2025-06-16 00:06:31.782556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4d5ca361d0'
down_revision = 'a41e2421f248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('ot_hours')

    # ### end Alembic commands ###
