"""add Da_duyet column

Revision ID: 3f6413999ca6
Revises: 000a6c7d74b5
Create Date: 2025-06-15 01:50:36.066834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6413999ca6'
down_revision = '000a6c7d74b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaCV', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Da_duyet', sa.Boolean(), nullable=True))
        batch_op.drop_column('Macv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Macv', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('Da_duyet')
        batch_op.drop_column('MaCV')

    # ### end Alembic commands ###
