"""Add employee_code and avatar

Revision ID: 8e26736955f3
Revises: a454d30e6efa
Create Date: 2025-06-02 18:14:14.593848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e26736955f3'
down_revision = 'a454d30e6efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_employee_code', ['employee_code'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar')
        batch_op.drop_column('employee_code')

    # ### end Alembic commands ###
