"""add pending employee info

Revision ID: a41e2421f248
Revises: 3f6413999ca6
Create Date: 2025-06-15 03:57:49.094567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41e2421f248'
down_revision = '3f6413999ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_employee_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MaNV', sa.String(length=20), nullable=False),
    sa.Column('TenNV', sa.String(length=100), nullable=False),
    sa.Column('SDT', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('Gioitinh', sa.String(length=10), nullable=True),
    sa.Column('NoiSinh', sa.String(length=100), nullable=True),
    sa.Column('QuocTich', sa.String(length=50), nullable=True),
    sa.Column('MAHD', sa.String(length=20), nullable=True),
    sa.Column('MaPB', sa.String(length=20), nullable=True),
    sa.Column('MaCV', sa.String(length=20), nullable=True),
    sa.Column('Luong', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('MaNV')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_employee_info')
    # ### end Alembic commands ###
